environments:
  - Development
  - Production

xcconfig:
    NATRIUM_OTHER_SWIFT_FLAGS:
        Development: $(inherited) -D DEVELOPMENT
        Production:  $(inherited) -D PRODUCTION
    NATRIUM_PRODUCT_BUNDLE_IDENTIFIER:
        Development: com.noljanolja.app.ios
        Production: com.ppnyy.nolgobulja
    NATRIUM_DISPLAY_NAME:
        Development: NolgoBulja Development
        Production: NolgoBulja
    NATRIUM_CURRENT_PROJECT_VERSION:
        Development: 1.0.6
        Production: 1.0.6
    NATRIUM_MARKETING_VERSION:
        Development: 1.0.6
        Production: 1.0.6
    NATRIUM_PROVISIONING_PROFILE_SPECIFIER:
        Development:
            Development: NolgoBulja-Dev-Development
            AppStore: NolgoBulja-Dev-Distribution
        Production:
            Development: NolgoBulja-AppStore-Development
            AppStore: NolgoBulja-AppStore-Distribution
    NATRIUM_GID_CLIENT_ID:
        Development: 954965503519-ajo51hke58jsfhalvonone0eujp65elr.apps.googleusercontent.com
        Production: 178013335305-u139pt1c45nv77u97shthoqi2tp0jafv.apps.googleusercontent.com
    NATRIUM_DOT_REVERSED_GID_CLIENT_ID:
        Development: com.googleusercontent.apps.954965503519-ajo51hke58jsfhalvonone0eujp65elr
        Production: com.googleusercontent.apps.178013335305-u139pt1c45nv77u97shthoqi2tp0jafv

files:
    Noljanolja/Configs/FireBases/GoogleService-Info.plist:
        Development: Noljanolja/Configs/FireBases/GoogleService-Info_Development.plist
        Production: Noljanolja/Configs/FireBases/GoogleService-Info_Production.plist

appicon:
    original: Noljanolja/Resources/Sources/ImageAssets.xcassets/AppIcon.appiconset/Source.png
    appiconset: Noljanolja/Resources/Sources/ImageAssets.xcassets/AppIcon.appiconset/
    all_sizes: false
    idioms:
        - ipad
        - iphone
    ribbon:
        Development: "Development"
        AppStore: ""

variables:
    baseUrl:
        Development: "http://dev.consumer-service.ppnyy.com/api"
        Production: "http://consumer-service.ppnyy.com/api"
    socketBaseUrl:
        Development: "ws://34.64.110.104/rsocket"
        Production: "ws://34.64.110.104/rsocket"
