environments:
  - Dev
  - AppStore

xcconfig:
    CONFIG_PRODUCT_BUNDLE_IDENTIFIER:
        Dev: com.noljanolja.app.ios
        AppStore: com.ppnyy.nolgobulja
    CONFIG_DISPLAY_NAME:
        Dev: NolgoBulja Dev
        AppStore: NolgoBulja

files:
    Noljanolja/Configs/FireBases/GoogleService-Info.plist:
        Dev: Noljanolja/Configs/FireBases/GoogleService-Info-Dev.plist
        AppStore: Noljanolja/Configs/FireBases/GoogleService-Info-AppStore.plist

appicon:
    original: Noljanolja/Resources/Sources/ImageAssets.xcassets/AppIcon.appiconset/Source.png
    appiconset: Noljanolja/Resources/Sources/ImageAssets.xcassets/AppIcon.appiconset/
    all_sizes: false
    idioms:
        - ipad
        - iphone
    ribbon:
        Dev: "Dev"
        AppStore: ""

variables:
    baseUrl:
        Dev: "http://dev.consumer-service.ppnyy.com/api"
        AppStore: "http://dev.consumer-service.ppnyy.com/api"
    socketBaseUrl:
        Dev: "ws://34.64.110.104/rsocket"
        AppStore: "ws://34.64.110.104/rsocket"
